/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import cliente.Cliente;
import metodos.Metodos;
/**
 *
 * @author MiguelGz
 */
public class Pago extends javax.swing.JFrame {

    /**
     * Creates new form Pago
     */
    Cliente alumno=new Cliente();
  Metodos metodos=new Metodos();
    public Pago() {
        initComponents();
        
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Compra en Linea");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jvolver = new javax.swing.JButton();
        btcompra = new javax.swing.JButton();
        Jlbltitle = new javax.swing.JLabel();
        jlbrhis = new javax.swing.JLabel();
        lblima1 = new javax.swing.JLabel();
        lbldato1 = new javax.swing.JLabel();
        lbldato2 = new javax.swing.JLabel();
        lbldato3 = new javax.swing.JLabel();
        lbldato4 = new javax.swing.JLabel();
        lbldato5 = new javax.swing.JLabel();
        txt5 = new javax.swing.JTextField();
        txt4 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txt1 = new javax.swing.JTextField();
        boxtipos = new javax.swing.JComboBox<>();
        imatarjeta = new javax.swing.JLabel();
        txt6 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jvolver.setText("Volver");
        jvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jvolverActionPerformed(evt);
            }
        });

        btcompra.setText("Comprar");
        btcompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcompraActionPerformed(evt);
            }
        });

        Jlbltitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Jlbltitle.setForeground(new java.awt.Color(0, 51, 204));
        Jlbltitle.setText("Pago con Tarjeta");

        jlbrhis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbrhis.setText("Aceptamos:");

        lblima1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Untitled2.jpg"))); // NOI18N

        lbldato1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbldato1.setText("Nombre del Titular");

        lbldato2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbldato2.setText("Numero de Tarjeta");

        lbldato3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbldato3.setText("Nombre de la  Ciudad");

        lbldato4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbldato4.setText("Fecha de Caducidad");

        lbldato5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbldato5.setText("CVV (Codigo de Seguridad)");

        boxtipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Otros Metodos de Pago", "Master Card", "Scotiabank", "Interbank", "BCP", " " }));
        boxtipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxtiposActionPerformed(evt);
            }
        });

        imatarjeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Untitled3.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jvolver, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btcompra, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Jlbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jlbrhis, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(lblima1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbldato1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbldato2)
                            .addComponent(lbldato5)
                            .addComponent(lbldato4))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt6, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(imatarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lbldato3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(boxtipos, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Jlbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jlbrhis)
                .addGap(13, 13, 13)
                .addComponent(lblima1)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbldato1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(lbldato2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(lbldato5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(lbldato4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(imatarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbldato3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(boxtipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jvolver, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btcompra, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jvolverActionPerformed
                TiendaClaro pepe = new TiendaClaro();
                pepe.setVisible(true);
                dispose();
                
                
                        
    }//GEN-LAST:event_jvolverActionPerformed

    private void btcompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcompraActionPerformed
  
        JOptionPane.showMessageDialog(null,"La Compra se ha realizado con exito.");
            volverosalir vs = new volverosalir();
            vs.setVisible(true);
    }//GEN-LAST:event_btcompraActionPerformed

    private void boxtiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxtiposActionPerformed
       int imagen =boxtipos.getSelectedIndex();
       switch (imagen){
           case 1:
               ImageIcon ima1=new ImageIcon(this.getClass().getResource("/imagenes/MC.jpg"));
               imatarjeta.setIcon(ima1);
               break;
           case 2:
               ImageIcon ima2=new ImageIcon(this.getClass().getResource("/imagenes/Scousha.jpg"));
               imatarjeta.setIcon(ima2);
               break;
           case 3:
               ImageIcon ima3=new ImageIcon(this.getClass().getResource("/imagenes/IBK.jpg"));
               imatarjeta.setIcon(ima3);
               break;
            case 4:
               ImageIcon ima4=new ImageIcon(this.getClass().getResource("/imagenes/bcp.jpg"));
               imatarjeta.setIcon(ima4);
               break;    
               
               
       }
    }//GEN-LAST:event_boxtiposActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pago().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jlbltitle;
    private javax.swing.JComboBox<String> boxtipos;
    private javax.swing.JButton btcompra;
    private javax.swing.JLabel imatarjeta;
    private javax.swing.JLabel jlbrhis;
    private javax.swing.JButton jvolver;
    public static javax.swing.JLabel lbldato1;
    private javax.swing.JLabel lbldato2;
    private javax.swing.JLabel lbldato3;
    private javax.swing.JLabel lbldato4;
    private javax.swing.JLabel lbldato5;
    private javax.swing.JLabel lblima1;
    public static javax.swing.JTextField txt1;
    public static javax.swing.JTextField txt2;
    public static javax.swing.JTextField txt4;
    public static javax.swing.JTextField txt5;
    public static javax.swing.JPasswordField txt6;
    // End of variables declaration//GEN-END:variables
}
